from __future__ import annotations

import asyncio
import time
from dataclasses import dataclass
from pathlib import Path
from threading import Event

from app.models.protocol import (
    EvidenceItem,
    LinkCandidate,
    LogEntry,
    ResultItemResponse,
    ResultPayload,
    RetrievalItem,
)
from app.services.http_sources import HttpSourceProvider, materials_root
from app.services.llm_client import DualModelLlmClient, is_llm_configured, load_llm_config
from app.services.pipeline import RetrievalPipeline
from app.services.source_profiles import SourceProfileLoader


@dataclass
class StubRetriever:
    delay_seconds: float = 0.02

    async def retrieve(
        self,
        item: RetrievalItem,
        *,
        cancel_event: Event | None = None,
        deadline: float | None = None,
    ) -> ResultItemResponse:
        started = time.monotonic()
        while time.monotonic() - started < self.delay_seconds:
            if cancel_event and cancel_event.is_set():
                return ResultItemResponse(
                    itemId=item.item_id,
                    status="failed",
                    confidence=0.0,
                    warnings=["job canceled"],
                    result=ResultPayload(notes="Job was canceled before retrieval completed."),
                    evidence=[],
                    linkCandidates=[],
                    imageCandidates=[],
                    logs=[LogEntry(message="retrieval canceled", itemId=item.item_id, level="warning")],
                )
            if deadline is not None and time.monotonic() > deadline:
                return ResultItemResponse(
                    itemId=item.item_id,
                    status="failed",
                    confidence=0.0,
                    warnings=["job timed out"],
                    result=ResultPayload(notes="Job timed out before retrieval completed."),
                    evidence=[],
                    linkCandidates=[],
                    imageCandidates=[],
                    logs=[LogEntry(message="retrieval timed out", itemId=item.item_id, level="error")],
                )
            await asyncio.sleep(0.005)

        result = ResultPayload(
            notes=f"Stub retrieval completed for {item.seed.title}.",
            links=[LinkCandidate(platform="other", url=f"https://example.invalid/{item.item_id}", title=item.seed.title)],
            images=[],
        )
        evidence = [
            EvidenceItem(
                field="notes",
                sourceUrl=f"https://example.invalid/{item.item_id}",
                sourceLabel="StubRetriever",
                confidence=0.61,
                note="Generated by stub pipeline for integration testing.",
            )
        ]
        logs = [LogEntry(message="stub retrieval finished", itemId=item.item_id)]
        return ResultItemResponse(
            itemId=item.item_id,
            status="succeeded",
            confidence=0.61,
            warnings=["stub result"],
            result=result,
            evidence=evidence,
            linkCandidates=result.links,
            imageCandidates=[],
            logs=logs,
        )


def build_default_retriever() -> RetrievalPipeline:
    llm_config = load_llm_config()
    llm_client = DualModelLlmClient(llm_config) if is_llm_configured(llm_config) else None
    source_provider = HttpSourceProvider(profile_loader=SourceProfileLoader(materials_root()))
    return RetrievalPipeline(source_provider=source_provider, llm_client=llm_client)
